# Generated by Django 2.1.5 on 2020-07-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeDetails',
        ),
    ]
