# Generated by Django 2.1.5 on 2020-07-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0002_auto_20200730_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
