# Generated by Django 2.1.5 on 2020-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0003_auto_20200731_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(upload_to='crud/images'),
        ),
    ]
